swagger: "2.0"
info:
  title: "Code4Teens REST API"
  version: "1.0.0"
basePath: "/api/v1"
consumes:
  - "application/json"
produces:
  - "application/json"

paths:
  /users:
    get:
      operationId: "user.get_all"
      tags:
        - "User"
      summary: "Returns all users"
      responses:
        200:
          description: "Success!"
          schema:
            type: "array"
            items:
              properties:
                id:
                  type: "integer"
                name:
                  type: "string"
                discriminator:
                  type: "string"
                display_name:
                  type: "string"
                is_admin:
                  type: "boolean"
                created_at:
                  type: "string"
                last_updated:
                  type: "string"
