swagger: "2.0"
info:
  title: Code4Teens REST API
  version: "1.0.0"
basePath: /api/v1
consumes:
  - application/json
produces:
  - application/json

paths:
  /users:
    get:
      operationId: user.get_all
      tags:
        - User
      summary: Returns all users
      responses:
        200:
          description: Success!
          schema:
            type: array
            items:
              properties:
                id:
                  type: integer
                name:
                  type: string
                discriminator:
                  type: string
                display_name:
                  type: string
                cohort_id:
                  type: integer
                is_admin:
                  type: boolean
                created_at:
                  type: string
                last_updated:
                  type: string
                bots:
                  type: array
                  items:
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      discriminator:
                        type: string
                      display_name:
                        type: string
                      msg_id:
                        type: integer
                      created_at:
                        type: string
                      last_updated:
                        type: string

    post:
      operationId: user.create
      tags:
        - User
      summary: Creates user
      parameters:
        - name: user_data
          in: body
          required: true
          schema:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              discriminator:
                type: string
              display_name:
                type: string
              cohort_id:
                type: integer
              is_admin:
                type: boolean
      responses:
        201:
          description: Success!
          schema:
            properties:
              id:
                type: integer
              name:
                type: string
              discriminator:
                type: string
              display_name:
                type: string
              cohort_id:
                type: integer
              is_admin:
                type: boolean
              created_at:
                type: string
              last_updated:
                type: string

  /users/{id}:
    get:
      operationId: user.get_one
      tags:
        - User
      summary: Returns user
      parameters:
        - name: id
          in: path
          type: integer
          required: true
      responses:
        200:
          description: Success!
          schema:
            type: object
            items:
              properties:
                id:
                  type: integer
                name:
                  type: string
                discriminator:
                  type: string
                display_name:
                  type: string
                cohort_id:
                  type: integer
                is_admin:
                  type: boolean
                created_at:
                  type: string
                last_updated:
                  type: string
                bots:
                  type: array
                  items:
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      discriminator:
                        type: string
                      display_name:
                        type: string
                      msg_id:
                        type: integer
                      created_at:
                        type: string
                      last_updated:
                        type: string

    put:
      operationId: user.update
      tags:
        - User
      summary: Updates user
      parameters:
        - name: id
          in: path
          type: integer
          required: true
        - name: user_data
          in: body
          schema:
            type: object
            properties:
              name:
                type: string
              discriminator:
                type: string
              display_name:
                type: string
              cohort_id:
                type: integer
              is_admin:
                type: boolean
      responses:
        200:
          description: Success!
          schema:
            type: object
            items:
              properties:
                id:
                  type: integer
                name:
                  type: string
                discriminator:
                  type: string
                display_name:
                  type: string
                cohort_id:
                  type: integer
                is_admin:
                  type: boolean
                created_at:
                  type: string
                last_updated:
                  type: string

    delete:
      operationId: user.delete
      tags:
        - User
      summary: Deletes user
      parameters:
        - name: id
          in: path
          type: integer
          required: true
      responses:
        200:
          description: Success!

  /bots:
    get:
      operationId: bot.get_all
      tags:
        - Bot
      summary: Returns all bots
      responses:
        200:
          description: Success!
          schema:
            type: array
            items:
              properties:
                id:
                  type: integer
                name:
                  type: string
                discriminator:
                  type: string
                display_name:
                  type: string
                user_id:
                  type: integer
                msg_id:
                  type: integer
                created_at:
                  type: string
                last_updated:
                  type: string
